# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10IUDKofZpoeC6seJOi5aGqEtKtnHYvfw
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import numpy as np

from sklearn.datasets import load_boston
boston=load_boston()
x=boston.data
y=boston.target
columns=boston.feature_names

df=pd.DataFrame(x)
df.columns=columns
df.describe()

df.shape

df.dropna()
df.shape

df['AGE']=df['AGE'].fillna(30)

df.head()

sns.boxplot(x=df['DIS'])

from matplotlib import pyplot as plt
fig,ax=plt.subplots(figsize=(16,8))
plt.scatter(x=df['INDUS'],y=df['TAX'])
ax.set_xlabel('proportion of non-retail business acre per town')
ax.set_ylabel('full-value property-tax per $10000')
plt.show()

z_score=np.abs(stats.zscore(df))
cln_df=df[(z_score<3).all(axis=1)]
cln_df.shape

q1=df.quantile(0.25)
q3=df.quantile(0.75)
IQR=q3-q1
df_IQRoutliers=df[~(df<(q1-1.5*IQR)|(df>(q3+1.5*IQR))).any(axis=1)]
df_IQRoutliers.shape

plt.figure(figsize=(16,8))
plt.hist(y)
plt.xlabel('Price')
plt.ylabel('Count')
plt.tight_layout

correlation_matrix=df.corr().round(2)
sns.heatmap(data=correlation_matrix,annot=True)

